# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        go build -ldflags="-s -w" symlink2file.go
        chmod +x symlink2file
      
    - name: Upload binary to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: symlink2file
        path: symlink2file
        retention-days: 1

  tests:
    needs: build
    runs-on: ubuntu-latest
    name: Install Bats with libs and runs tests
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: ${{ github.workspace }}/test/test_helper/bats-support
          assert-path:  ${{ github.workspace }}/test/test_helper/bats-assert
          file-path:    ${{ github.workspace }}/test/test_helper/bats-file

      - name: Download the binary from artifacts
        uses: actions/download-artifact@v4
        with:
          name: symlink2file

      - name: Test
        run: |
          pwd
          chmod +x symlink2file 
          ls -lh
          bats test/test.bats

