name: "Tests"
on: [push]

jobs:
   tests:
     runs-on: ubuntu-latest
     name: Install Bats with libs and runs tests
     steps:

       - name: Checkout
         uses: actions/checkout@v2

       - name: Setup Bats and bats libs
         uses: bats-core/bats-action@1.5.4

       - name: Test
         run: ./test/bats/bin/bats test/test.bats
